### PR TITLE
Update for Gnome Shell 42

### PR DESCRIPTION
**Pull request by nono031**
I don't know if this modification will break a previous version of gnome shell but it fix the #31 issue

### CODE REVIEW

**Comment by nono031** [comment]
image

**Comment by nono031** [comment]
I also used xml output of nvidia-smi which opens a door for a very detailed information

**Comment by sanyer** [comment]
We need you, sir @andr3slelouch

**Comment by andr3slelouch** [comment]
> We need you, sir @andr3slelouch

I'm sorry for that I was a little busy but I'm back and i will try to make it available for gnome 42 as soon as possible

**Comment by sanyer** [comment]
@andr3slelouch no worries! Thanks for coming back :-D

**Pull request merged**
